### ISSUE TITLE
onlyKilledRE error

### ISSUE THREAD

**Issue by chenshifei** [dtmilano/AndroidViewClient#140]
Hi, I'm now using SONY Z1 with stock Lollipop 5.0.2. Everytime when I execute `dump` it fails with these messages,

    Traceback (most recent call last):
      File "dump", line 175, in <module>
        vc.dump(window=options[WINDOW])
      File "/Users/johnchen/Repo/AndroidViewClient/src/com/dtmilano/android/viewclient.py", line 3073, in dump
        raise RuntimeError('''ERROR: UiAutomator output contains no valid information. UiAutomator was killed, no reason given.''' + extraInfo)
    RuntimeError: ERROR: UiAutomator output contains no valid information. UiAutomator was killed, no reason given.

Here's a part of the original `received` message from UIAutomator,

    ...bounds="[809,1603][1078,1768]"><node index="0" text="??" resource-id="android:id/title" class="android.widget.TextView" package="com.dianping.v1" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="true" bounds="[821,1600][1066,1759]" /></node></node></node><node index="1" text="" resource-id="com.dianping.v1:id/iv_titleshadow" class="android.widget.ImageView" package="com.dianping.v1" content-desc="???title??" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,225][1080,234]" /></node></hierarchy>Killed

As you can see "Killed" was appended and causes `onlyKilledRE` to raise an exception.

I suppose `onlyKilledRE` should be used to detect if the output contains "Killed" only. Could you take a look at this? Thanks in advance!

**Comment by dtmilano** [comment]
Are you setting `ignoreuiautomatorkilled=True` when creating the `ViewClient` object?

**Comment by chenshifei** [comment]
Yes, `kwargs2` shows below,

    {'startviewserver': True, 'forceviewserveruse': False, 'autodump': False, 'ignoreuiautomatorkilled': True}
