### ISSUE TITLE
RuntimeError: The views are being refreshed too frequently to dump.

### ISSUE THREAD

**Issue by eromoe** [dtmilano/AndroidViewClient#189]
I meet this error when I in a app page.
I don't see any refreshing, but it still raise this error

```
Traceback (most recent call last):
  File "C:/Python27/Scripts/culebra", line 4, in <module>
    __import__('pkg_resources').run_script('androidviewclient==11.5.3', 'culebra')
  File "C:\python27\lib\site-packages\pkg_resources\__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\python27\lib\site-packages\pkg_resources\__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "c:\python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\EGG-INFO\scripts\culebra", line 1272, in <module>
    vc.dump(window=options[CulebraOptions.WINDOW])
  File "C:\python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\com\dtmilano\android\viewclient.py", line 3266, in dump
    raise RuntimeError('''The views are being refreshed too frequently to dump.''')
RuntimeError: The views are being refreshed too frequently to dump.

```

**Comment by VasilijSviridov** [comment]
same here :/

**Comment by dtmilano** [comment]
Can you provide some means of reproducing it?

**Comment by VasilijSviridov** [comment]
I am using dump to get tree, also as I understand dump is an extension of adb shell uiautomator dump ? 

  File "/Library/Python/2.7/site-packages/androidviewclient-13.3.1-py2.7.egg/EGG-INFO/scripts/dump", line 222, in <module>
    vc.dump(window=options[WINDOW])
  File "/Library/Python/2.7/site-packages/androidviewclient-13.3.1-py2.7.egg/com/dtmilano/android/viewclient.py", line 3318, in dump
    raise RuntimeError('''The views are being refreshed too frequently to dump.''')
RuntimeError: The views are being refreshed too frequently to dump.

**Comment by VasilijSviridov** [comment]
on adb side am getting ERROR: could not get idle state., and thought that might be your solution will help to get tree, but suppose the issue is same.

**Comment by gchen36** [comment]
Some apk packages can trigger the issue. I found one, its package name is "ru.zzzzz.Clock12purr"

<img width="1138" alt="screen shot 2017-11-08 at 4 43 16 pm" src="https://user-images.githubusercontent.com/2905460/32576126-f5b3353e-c4a3-11e7-878a-1115c71edf06.png">

**Comment by gchen36** [comment]
[ru.zzzzz.Clock12purr-4.apk.zip](https://github.com/dtmilano/AndroidViewClient/files/1455521/ru.zzzzz.Clock12purr-4.apk.zip)

**Comment by dtmilano** [comment]
Unfortunately, this is a limitation of *UiAutomator*, which is what AndroidViewClient/culebra uses as backend. It needs some idle time to be able to get the dump, and this doesn't happen when an animation is constantly being updated.

**Comment by dtmilano** [comment]
https://github.com/dtmilano/CulebraTester2-public is not affected by this problem.

It can be used to dump the hierarchy and also as an AndroidViewClient backend.
