### ISSUE TITLE
raise AttributeError, name, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mjdev** [dtmilano/AndroidViewClient#196]
```

/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/bin/python3.5 /Volumes/MacintoshHD/main.py
Traceback (most recent call last):
  File "/Volumes/MacintoshHD/main.py", line 19, in <module>
    from com.dtmilano.android.viewclient import ViewClient
  File "/usr/local/lib/python3.5/site-packages/com/dtmilano/android/viewclient.py", line 383
    raise AttributeError, name
                        ^
SyntaxError: invalid syntax

Process finished with exit code 1
```

**Comment by dtmilano** [comment]
You should use **python 2.x** to run AndroidViewClient/culebra.
Python 3.x is not supported.

**Comment by mjdev** [comment]
Do you have a time frame when it will be?
