### ISSUE TITLE
AdbClient.shell() function tends to be crashed for multi-threading usage.

### ISSUE THREAD

**Issue by HW-Lee** [dtmilano/AndroidViewClient#232]
As titled, it seems that the API AdbClient.shell() does not handle the situation when multiple threads try to call the API. It might crash the socket to the device and the function will not work after crashed.
Therefore, I suggest to add a threading.Lock() variable in the AdbClient class for protecting all the functions that cannot be called simultaneously by multiple threads.

**Comment by dtmilano** [comment]
Can you please describe the scenario in more detail?
Multiple threads invoking `AdbClient.shell()` using a single connection to a single device?

**Comment by dtmilano** [comment]
If you have a script to reproduce the issue it would be even better.

**Comment by HW-Lee** [comment]
Please check the code below:
```python
from com.dtmilano.android.viewclient import ViewClient
import subprocess
import threading
import time


def run():
    device, serialno = ViewClient.connectToDeviceOrExit(serialno=None)

    t1 = TestThread(device, "whatever.intent1")
    t2 = TestThread(device, "whatever.intent2")

    t1.start()
    t2.start()

    vc = ViewClient(device, serialno)

    time.sleep(10)

    t1.join()
    t2.join()


class TestThread(threading.Thread):
    def __init__(self, device, intent_name):
        super(TestThread, self).__init__()
        self.daemon = True
        self.stoprequest = threading.Event()
        self.device = device
        self.intent_name = intent_name

    def run(self):
        while not self.stoprequest.isSet():
            if True:
            # try:
                # It causes broken pipe exception
                self.device.shell("am broadcast -a {}".format(self.intent_name))

                # It works well
                # subprocess.Popen("adb shell am broadcast -a {}".format(self.intent_name).split(), stdout=subprocess.PIPE).communicate()
            # except Exception as e:
            #   print(e)
            time.sleep(0.1)

    def join(self, timeout=None):
        self.stoprequest.set()
        super(TestThread, self).join(timeout)


if __name__ == "__main__":
    try:
        run()
    except Exception as e:
        print(e)
```

I created 2 threads that shares the same `device` and `serialno`, which means they might communicate with the same device at the same time. In the implementation, I simply send an arbitrary intent every 100 ms. After running above implementation, I got

```
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "crash-test.py", line 37, in run
    self.device.shell("am broadcast -a {}".format(self.intent_name))
  File "/home/hw_lee/github-projects/AAT-dev/AudioAutoTest/venv/py2/local/lib/python2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 472, in shell
    self.__send('shell:%s' % cmd, checkok=True, reconnect=False)
  File "/home/hw_lee/github-projects/AAT-dev/AudioAutoTest/venv/py2/local/lib/python2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 279, in __send
    self.__checkOk()
  File "/home/hw_lee/github-projects/AAT-dev/AudioAutoTest/venv/py2/local/lib/python2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 331, in __checkOk
    error = sock.recv(1024)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "crash-test.py", line 37, in run
    self.device.shell("am broadcast -a {}".format(self.intent_name))
  File "/home/hw_lee/github-projects/AAT-dev/AudioAutoTest/venv/py2/local/lib/python2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 472, in shell
    self.__send('shell:%s' % cmd, checkok=True, reconnect=False)
  File "/home/hw_lee/github-projects/AAT-dev/AudioAutoTest/venv/py2/local/lib/python2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 279, in __send
    self.__checkOk()
  File "/home/hw_lee/github-projects/AAT-dev/AudioAutoTest/venv/py2/local/lib/python2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 331, in __checkOk
    error = sock.recv(1024)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

invalid literal for int() with base 10: 'Broadcasting: Intent { act=whatever.intent1 flg=0x400000 }\nBroadcast completed: result=0'
```
I found that the issue might be solved by regarding the API AdbClient.shell() as a critical section:
```python
def run():
    device, serialno = ViewClient.connectToDeviceOrExit(serialno=None)

    # Try to protect the critical section
    device.lock = threading.Lock()
    t1 = TestThread(device, "whatever.intent1")
    t2 = TestThread(device, "whatever.intent2")
```
```python
    # Try to protect the critical section
    device.lock.acquire()
    vc = ViewClient(device, serialno)
    device.lock.release()
```
```python
class TestThread(threading.Thread):
    def run(self):
        while not self.stoprequest.isSet():
            if True:
            # try:
                # It causes broken pipe exception
                # Try to protect the critical section
                self.device.lock.acquire()
                self.device.shell("am broadcast -a {}".format(self.intent_name))
                self.device.lock.release()
```

Let me know if there is anything else ambiguous :)
