### ISSUE TITLE
dump-simple.py has "Traceback" and "socket.error: [Errno 32] Broken pipe"

### ISSUE THREAD

**Issue by yamatakau08** [dtmilano/AndroidViewClient#237]
Could you supporte me to remove 
**Traceback message**
**socket.error: [Errno 32] Broken pipe**
when dump-simple.py execute ?
 
[environment]
```
yama@roswell:/usr/local/lib/python/AndroidViewClient-13.6.2/examples$ uname -a
CYGWIN_NT-6.1 roswell 2.8.2(0.313/5/3) 2017-07-12 10:58 x86_64 Cygwin
yama@roswell:/usr/local/lib/python/AndroidViewClient-13.6.2/examples$ python --version
Python 2.7.13
yama@roswell:/usr/local/lib/python/AndroidViewClient-13.6.2/examples$ echo $ANDROID_VIEW_CLIENT_HOME
/usr/local/lib/python/AndroidViewClient-13.6.2/
```
[check-import]
```
yama@roswell:/usr/local/lib/python/AndroidViewClient-13.6.2/examples$ python check-import.py --debug
sys.path= ['/usr/local/lib/python/AndroidViewClient-13.6.2/examples', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-cygwin', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/site-packages', '/usr/local/lib/python/AndroidViewClient-13.6.2/src']
OK
```
[dump-simple.py]
```
yama@roswell:/usr/local/lib/python/AndroidViewClient-13.6.2/examples$ ./dump-simple.py
Connecting to a device with serialno=.* with a timeout of 60 secs...
Connected to device with serialno=.*
Actual device serialno=CB5A224CBF
Traceback (most recent call last):
  File "./dump-simple.py", line 28, in <module>
    ViewClient(*ViewClient.connectToDeviceOrExit(verbose=True)).traverse(transform=ViewClient.TRAVERSE_CIT)
  File "/usr/local/lib/python/AndroidViewClient-13.6.2/src/com/dtmilano/android/viewclient.py", line 2576, in __init__
    self.dump()
  File "/usr/local/lib/python/AndroidViewClient-13.6.2/src/com/dtmilano/android/viewclient.py", line 3276, in dump
    received = self.device.shell(cmd)
  File "/usr/local/lib/python/AndroidViewClient-13.6.2/src/com/dtmilano/android/adb/adbclient.py", line 474, in shell
    self.__send('shell:%s' % cmd, checkok=True, reconnect=False)
  File "/usr/local/lib/python/AndroidViewClient-13.6.2/src/com/dtmilano/android/adb/adbclient.py", line 278, in __send
    self.socket.send('%04X%s' % (len(b), b))
socket.error: [Errno 32] Broken pipe
```

**Comment by dtmilano** [comment]
Does `dump` (https://github.com/dtmilano/AndroidViewClient/blob/master/tools/dump) work?

**Comment by yamatakau08** [comment]
"dump" puts out the following is same as the above post.

yama@roswell:/cygdrive/c/temp/AndroidViewClient/AndroidViewClient-13.6.2/tools$ ./dump
Traceback (most recent call last):
  File "./dump", line 230, in <module>
    vc.dump(window=options[WINDOW])
  File "/usr/local/lib/python/AndroidViewClient-13.6.2/src/com/dtmilano/android/viewclient.py", line 3276, in dump
    received = self.device.shell(cmd)
  File "/usr/local/lib/python/AndroidViewClient-13.6.2/src/com/dtmilano/android/adb/adbclient.py", line 474, in shell
    self.__send('shell:%s' % cmd, checkok=True, reconnect=False)
  File "/usr/local/lib/python/AndroidViewClient-13.6.2/src/com/dtmilano/android/adb/adbclient.py", line 278, in __send
    self.socket.send('%04X%s' % (len(b), b))
socket.error: [Errno 32] Broken pipe

**Comment by yamatakau08** [comment]
Dear dtmilano,

Have you tried AndroidViewClient on Cygwin , Windows 7 or 8?
Did it work well?

**Comment by yamatakau08** [comment]
I assume root cause in **Cygwin** environment.

**Comment by yamatakau08** [comment]
I tried with Python Windows version both 3.6.4 and 2.7.14.

Version **2.7.14** works fine.
```C:\Users\0000910700>set ANDROID_VIEW_CLIENT_HOME=C:\temp\AndroidViewClient\AndroidViewClient-13.6.2
C:\Users\0000910700>cd %ANDROID_VIEW_CLIENT_HOME%
C:\temp\AndroidViewClient\AndroidViewClient-13.6.2>cd tools
C:\temp\AndroidViewClient\AndroidViewClient-13.6.2\tools>C:\winbin\Python27\python.exe --version
Python 2.7.14
C:\temp\AndroidViewClient\AndroidViewClient-13.6.2\tools>C:\winbin\Python27\python.exe dump -V
Connecting to a device with serialno=.* with a timeout of 60 secs...
Connected to device with serialno=.*
Actual device serialno=CB5A224CBF
android.widget.FrameLayout
   android.widget.FrameLayout com.spotify.music:id/slate_chrome_container
      android.widget.FrameLayout com.spotify.music:id/slate_content_container
         android.widget.TextView com.spotify.music:id/title You discovered a Premium feature!
         android.widget.TextView com.spotify.music:id/message Upgrading to Spotify Premium will unlock it.
         android.widget.TextView com.spotify.music:id/action_button Get Premium Now
         android.widget.TextView com.spotify.music:id/legal_text Terms and Conditions apply. Learn more
      android.widget.TextView com.spotify.music:id/simple_text_upsell Premium Feature
      android.widget.TextView com.spotify.music:id/simple_text_upsell LATER
```

Version 3.6.4 does **NOT work**! 
I guess this version is for 32bit python in official download page where I got.

```
C:\Users\0000910700>set ANDROID_VIEW_CLIENT_HOME=C:\temp\AndroidViewClient\AndroidViewClient-13.6.2
C:\Users\0000910700>cd %ANDROID_VIEW_CLIENT_HOME%
C:\temp\AndroidViewClient\AndroidViewClient-13.6.2>cd tools
C:\temp\AndroidViewClient\AndroidViewClient-13.6.2\tools>C:\winbin\Python36-32\python.exe --version
Python 3.6.4
C:\temp\AndroidViewClient\AndroidViewClient-13.6.2\tools>C:\winbin\Python36-32\python.exe dump -V
  File "dump", line 140
    print progname, __version__
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int progname, __version__)?
```

**Comment by dtmilano** [comment]
Your comments are correct. *AndroidViewClient* works on python 2.x, version 3.x not supported yet.

The other problem seems to be caused by the python script not being able to connect to the adb port.
Firewall issues?

**Comment by yamatakau08** [comment]
Dear dtmilano,

> Firewall issues?

I connected Android device **DIRECTLY with USB cable.**
In this case, Firewall settings makes the problem?

The following output is on Cygwin envrionment

Do you have any hint?

```
yama@roswell:~$ type adb
adb はハッシュされています (/cygdrive/c/Users/0000910700/AppData/Local/Android/sdk/platform-tools/adb)
yama@roswell:~$ adb version
Android Debug Bridge version 1.0.39
Version 27.0.0-4455170
Installed as C:\Users\0000910700\AppData\Local\Android\sdk\platform-tools\adb.exe
yama@roswell:~$ adb devices
List of devices attached
CB5A224CBF      device
yama@roswell:~$ adb logcat
--------- beginning of crash
F/libc    (13222): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x94e0100c in tid 13432 (RenderThread)
F/google-breakpad(10373): Microdump skipped (uninteresting)
F/libc    (15128): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x979e900c in tid 15206 (RenderThread)
I/DEBUG   (  336): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  336): UUID: 7be6285a-8564-49b4-bf49-3a0090471622
I/DEBUG   (  336): Build fingerprint: 'KDDI/SOL26_jp_kdi/SOL26:5.0.2/23.1.G.2.244/4117346806:user/release-keys'
I/DEBUG   (  336): Revision: '0'
I/DEBUG   (  336): ABI: 'arm'
I/DEBUG   (  336): pid: 15128, tid: 15206, name: RenderThread  >>> com.kouzoh.mercari <<<
I/DEBUG   (  336): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x979e900c
I/DEBUG   (  336):     r0 979e93cc  r1 00000080  r2 979e900c  r3 00000078
```

**Comment by dtmilano** [comment]
I understand from your comment

> Version 2.7.14 works fine.

and the `dump` output that it was working with that version.
