### ISSUE TITLE
Culebra GUI not running . 

### ISSUE THREAD

**Issue by wgy-home** [dtmilano/AndroidViewClient#275]
version: 
```shell
python --version  
Python 2.7.15
culebra --version 
culebra 15.8.1

system version : macOS catalina  10.15.3 
phone : xiaomi6
```

error log 
```shell
culebra  -G                                                                                                                            ✔  10113  16:29:35
#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
Copyright (C) 2013-2018  Diego Torres Milano
Created on 2020-03-25 by Culebra v15.8.1
                      __    __    __    __
                     /  \  /  \  /  \  /  \
____________________/  __\/  __\/  __\/  __\_____________________________
___________________/  /__/  /__/  /__/  /________________________________
                   | / \   / \   / \   / \   \___
                   |/   \_/   \_/   \_/   \    o \
                                           \_____/--<
@author: Diego Torres Milano
@author: Jennifer E. Swofford (ascii art snake)
"""


import re
import sys
import os

from com.dtmilano.android.viewclient import ViewClient

TAG = 'CULEBRA'

_s = 5
_v = '--verbose' in sys.argv


kwargs1 = {'ignoreversioncheck': False, 'verbose': False, 'ignoresecuredevice': False}
device, serialno = ViewClient.connectToDeviceOrExit(**kwargs1)
kwargs2 = {'forceviewserveruse': False, 'useuiautomatorhelper': False, 'ignoreuiautomatorkilled': True, 'autodump': False, 'debug': {}, 'startviewserver': True, 'compresseddump': True}
vc = ViewClient(device, serialno, **kwargs2)
#vc.dump(window='-1') # FIXME: seems not needed

Traceback (most recent call last):
  File "/usr/local/bin/culebra", line 1411, in <module>
    vc.dump(window=options[CulebraOptions.WINDOW])
  File "/usr/local/lib/python2.7/site-packages/com/dtmilano/android/viewclient.py", line 3344, in dump
    self.setViewsFromUiAutomatorDump(received)
  File "/usr/local/lib/python2.7/site-packages/com/dtmilano/android/viewclient.py", line 2983, in setViewsFromUiAutomatorDump
    self.__parseTreeFromUiAutomatorDump(received)
  File "/usr/local/lib/python2.7/site-packages/com/dtmilano/android/viewclient.py", line 3165, in __parseTreeFromUiAutomatorDump
    raise ValueError("received does not contain valid XML: " + receivedXml)
ValueError: received does not contain valid XML: ERROR: null root node returned by UiTestAutomationBridge.
```

Please tell me the reason, Thanks .

**Comment by dtmilano** [comment]
Use python3
