### ISSUE TITLE
Exception: adb="adb.exe" is not executable. 

### ISSUE THREAD

**Issue by canercetin-randomguy** [dtmilano/AndroidViewClient#306]
```
E
======================================================================
ERROR: testSomething (__main__.CulebraTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\emosc\PycharmProjects\pythonProject\main.py", line 49, in setUp
    super(CulebraTests, self).setUp()
  File "C:\Users\emosc\PycharmProjects\pythonProject\venv\lib\site-packages\com\dtmilano\android\viewclient.py", line 4914, in setUp
    self.vc = ViewClient("UI_AUTOMATOR_HELPER_DEVICE", "UI_AUTOMATOR_HELPER_SERIALNO", **self.kwargs2)
  File "C:\Users\emosc\PycharmProjects\pythonProject\venv\lib\site-packages\com\dtmilano\android\viewclient.py", line 2604, in __init__
    self.uiAutomatorHelper = UiAutomatorHelper(device, localport=localport, remoteport=remoteport)
  File "C:\Users\emosc\PycharmProjects\pythonProject\venv\lib\site-packages\com\dtmilano\android\uiautomator\uiautomatorhelper.py", line 119, in __init__
    self.adb = self.__whichAdb(adb)
  File "C:\Users\emosc\PycharmProjects\pythonProject\venv\lib\site-packages\com\dtmilano\android\uiautomator\uiautomatorhelper.py", line 180, in __whichAdb
    adb = obtainAdbPath()
  File "C:\Users\emosc\PycharmProjects\pythonProject\venv\lib\site-packages\com\dtmilano\android\common.py", line 166, in obtainAdbPath
    raise Exception('''adb="%s" is not executable. %s
Exception: adb="adb.exe" is not executable. 

These files we unsuccessfully checked to find a suitable 'adb.exe' executable:
    D:\platform-tools_r33.0.2-windows\platform-tools\platform-tools\adb.exe
    android\platform-tools\adb.exe
    android-sdk\platform-tools\adb.exe
    C:\Program Files\Androidndroid-sdk\platform-tools\adb.exe
    C:\Program Files (x86)\Androidndroid-sdk\platform-tools\adb.exe
    adb.exe
    C:\Users\emosc\PycharmProjects\pythonProject\venv\Scripts\adb.exe
    C:\Program Files (x86)\Common Files\Oracle\Java\javapath\adb.exe
    C:\Windows\system32\adb.exe
    C:\Windows\adb.exe
    C:\Windows\System32\Wbem\adb.exe
    C:\Windows\System32\WindowsPowerShell\v1.0\adb.exe
    C:\Windows\System32\OpenSSH\adb.exe
    C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\adb.exe
    C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\adb.exe
    C:\Program Files\dotnet\adb.exe
    C:\Program Files (x86)\Ghdl\Bin\adb.exe
    C\adb.exe
    C:\Program Files\Git\cmd\adb.exe
    D:\chromedriver_win32\adb.exe
    C:\Program Files\nodejs\adb.exe
    D:\Go\bin\adb.exe
    C:\Program Files\MySQL\MySQL Shell 8.0\bin\adb.exe
    C:\Users\emosc\AppData\Local\Programs\Python\Python310\Scripts\adb.exe
    C:\Users\emosc\AppData\Local\Programs\Python\Python310\adb.exe
    C:\Users\emosc\AppData\Local\Programs\Python\Python39\Scripts\adb.exe
    C:\Users\emosc\AppData\Local\Programs\Python\Python39\adb.exe
    C:\Program Files\aircrack-ng-1.2-win\bin\adb.exe
    C:\Program Files\JetBrains\CLion 2021.3\bin\adb.exe
    adb.exe
    D:\questa_fse\win64\adb.exe
    C:\Program Files\JetBrains\PyCharm Community Edition 2021.3\bin\adb.exe
    adb.exe
    D:\Quartus\questa_fse\win64\adb.exe
    C:\cygwin64\bin\adb.exe
    adb.exe
    C:\Users\emosc\AppData\Local\Programs\Microsoft VS Code\bin\adb.exe
    C:\Users\emosc\AppData\Roaming\npm\adb.exe
    C:\Users\emosc\go\bin\adb.exe
    D:\GoLand 2022.1.3\bin\adb.exe
    adb.exe
    

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)
```

ADB.exe is downloaded on D:\platform-tools_r33.0.2-windows\platform-tools, https://prnt.sc/alncfU9aCxcS

Added folder to the env, https://prnt.sc/RBlgw47MFRW9

Still getting errors. Help?

***downloaded ADB from https://dl.google.com/android/repository/platform-tools-latest-windows.zip

***downloaded ADB from https://developer.android.com/studio/releases/platform-tools#downloads same error. 

***downloaded ADB from https://adb.clockworkmod.com/, same error. where the hell do I need to download this to be "suitable"?

***downloaded ADB from softonic. yeah. didnt work. https://adb-driver-installer.softonic.com.tr/

**Comment by dtmilano** [comment]
`adb` should be working before the tests have a chance to run.

Install `adb` (I would recommend the official site) and then try

```
adb devices
```

or something similar to verify it's working.
