### ISSUE TITLE
[Bug] `dump -a` throws error

### ISSUE THREAD

**Issue by KaKi87** [dtmilano/AndroidViewClient#324]
Hello,

When running `dump -a` on a Linux computer connected via wireless ADB to an Android 6.0.1 device, the following is output :

```
Traceback (most recent call last):
  File "~/.local/bin/dump", line 221, in <module>
    vc.dump(window=options[WINDOW])
  File "~/.local/pipx/venvs/androidviewclient/lib/python3.11/site-packages/com/dtmilano/android/viewclient.py", line 3546, in dump
    received = self.device.shell(cmd)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/pipx/venvs/androidviewclient/lib/python3.11/site-packages/com/dtmilano/android/adb/adbclient.py", line 584, in shell
    self.__send('shell:%s' % _cmd, checkok=True, reconnect=False)
  File "~/.local/pipx/venvs/androidviewclient/lib/python3.11/site-packages/com/dtmilano/android/adb/adbclient.py", line 364, in __send
    self.__checkOk()
  File "~/.local/pipx/venvs/androidviewclient/lib/python3.11/site-packages/com/dtmilano/android/adb/adbclient.py", line 428, in __checkOk
    raise RuntimeError("ERROR: %s %s" % (repr(recv), error))
RuntimeError: ERROR: b'' b''
```

Thanks

**Comment by dtmilano** [comment]
Can you see the device connected when you run `adb devices` ?
Can you access the device via `adb shell` ?

**Comment by KaKi87** [comment]
Of course.

**Comment by dtmilano** [comment]
I installed an emulator with API 23, launched and then `dump -a` and everything works as expected

```
 dump -a
View[ class=android.widget.FrameLayout index=0 text= resource-id= class=android.widget.FrameLayout package=com.android.launcher3 content-desc= checkable=false checked=false clickable=false enabled=true focusable=false focused=false scrollable=false long-clickable=false password=false selected=false bounds=((0, 0), (1080, 1794)) uniqueId=id/no_id/1 ]   parent=None
   View[ class=com.android.launcher3.Workspace index=0 text= resource-id=com.android.launcher3:id/workspace class=com.android.launcher3.Workspace package=com.android.launcher3 content-desc= checkable=false checked=false clickable=false enabled=true focusable=false focused=false scrollable=true long-clickable=false password=false selected=false bounds=((0, 0), (1080, 1794)) uniqueId=id/no_id/2 ]   parent=android.widget.FrameLayout
      View[ class=android.appwidget.AppWidgetHostView index=0 text= resource-id= class=android.appwidget.AppWidgetHostView package=com.android.launcher3 content-desc=Analog clock checkable=false checked=false clickable=false enabled=true focusable=false focused=false scrollable=false long-clickable=true password=false selected=false bounds=((224, 242), (646, 748)) uniqueId=id/no_id/3 ]   parent=com.android.launcher3.Workspace
         View[ class=android.view.View index=0 text= resource-id=com.android.deskclock:id/analog_appwidget class=android.view.View package=com.android.deskclock content-desc=19:22 checkable=false checked=false clickable=true enabled=true focusable=false focused=false scrollable=false long-clickable=false password=false selected=false bounds=((245, 263), (625, 727)) uniqueId=id/no_id/4 ]   parent=android.appwidget.AppWidgetHostView
...
```

**Comment by KaKi87** [comment]
Can I please have help finding out solving this issue on my machine ?

**Comment by dtmilano** [comment]
- Use a newer `python` (i.e. 3.11)
- Create a virtual environment
- Install **Culebra/AndroidViewClient** using `pip`
- Create a new android emulator using an image with API level 23 (as you mentioned)
- Check `adb devices`
- Run `dump -a`
