### ISSUE TITLE
ValueError: unrecognized mode in takeSnaphot()

### ISSUE THREAD

**Issue by Diob** [dtmilano/AndroidViewClient#62]
if bpp = 32

the mode is set to AGR. This in an invalid and not recognized mode.
There seems to be something wrong in the next line where the sorting is done. if sorted is removed, Then the mode becomes RGA

**Comment by yoonsukchang** [comment]
The issue persists in version 13.4.0. Here is what I am getting:

`Traceback (most recent call last):
  File "android_view_client_example.py", line 94, in <module>
    takeScreenshot(device1, device1Serial)
  File "android_view_client_example.py", line 79, in takeScreenshot
    device.takeSnapshot(reconnect=True).save('/sdcard/uiengine/bugreport/' + deviceSerial + '_' + date + '.png', 'PNG')
  File "C:\AndroidViewClient-master\src\com\dtmilano\android\adb\adbclient.py", line 790, in takeSnapshot
    image = Image.frombuffer(mode, (width, height), received, 'raw', argMode, 0, 1)
  File "build\bdist.win32\egg\PIL\Image.py", line 2333, in frombuffer
  File "build\bdist.win32\egg\PIL\Image.py", line 2265, in frombytes
  File "build\bdist.win32\egg\PIL\Image.py", line 2229, in new
ValueError: unrecognized mode`

**Comment by dtmilano** [comment]
Can you attach the script you are using?
Also, info about the device, android version, etc. so the problem can be reproduced.

**Comment by yoonsukchang** [comment]
Thank you for getting back to me. Here is the following code I used:

`def takeScreenshot(device, deviceSerial):
	timestamp = time.time()
	date = datetime.datetime.fromtimestamp(timestamp).strftime('%Y%m%d%H%M%S')
	device.shell('mkdir /sdcard/uiengine/screenshot')
	device.takeSnapshot(reconnect=True).save('/sdcard/uiengine/bugreport/' + deviceSerial + '_' + date + '.png', 'PNG')

	print("Screenshot has been taken")	

takeScreenshot(device1, device1Serial)`

The device I am using is the H871 (LG G6 AT&T) with Android version 7.0.

**Comment by dtmilano** [comment]
You can enable `DEBUG` in `adbclient.py` (line 53):

`DEBUG = True`

and check the debug messages produced.
This will help us understand the problem better.

**Comment by dtmilano** [comment]
Also, in your script you can do

```
import com.dtmilano.android.adb.adbclient
com.dtmilano.android.adb.adbclient.DEBUG = True
device.takeSnapshot(reconnect=True).save("fimage.png")
```

and check the debug output
